#!/bin/bash
EXISTING_RYU_PID=`ps aux | grep ryu-manager | grep python | awk '{print $2}'`

if [[ -z ${EXISTING_RYU_PID} ]]; then
    screen -S ryu -d -m ryu-manager --flagfile /etc/ryu/ryu.conf ryu.app.simple_switch,ryu.app.ofctl_rest
    sleep 1
    EXISTING_RYU_PID=`ps aux | grep ryu-manager | grep python | awk '{print $2}'`
    echo "Started new Ryu instance with PID ${EXISTING_RYU_PID}"
else
    echo "An instance of Ryu is already running with PID ${EXISTING_RYU_PID}"
fi
