#!/bin/bash

function command_desc() {
    echo -e "\e[1;33;40m$1\e[0m"
    read -p "Press [Enter] key to continue..."
}

# Sets the 'STRING' and 'FLAGS' environment variables
function setFlagsString() {
    if [ "$1" = "-n" ]; then
        STRING=$2
        FLAGS=-ne
    else
        STRING=$1
        FLAGS=-e
    fi
}

function green() {
    setFlagsString "$1" "$2"
    echo $FLAGS "\e[1;32;40m${STRING}\e[0m"
}

function blue() {
    setFlagsString "$1" "$2"
    echo $FLAGS "\e[1;34;40m${STRING}\e[0m"
}

function yellow() {
    setFlagsString "$1" "$2"
    echo $FLAGS "\e[1;33;40m${STRING}\e[0m"
}

function red() {
    setFlagsString "$1" "$2"
    echo $FLAGS "\e[1;31;40m${STRING}\e[0m"
}

function green_title() {
    echo
    echo "======================================================"
    echo -e "\e[1;92;40m$1\e[0m"
    echo "------------------------------------------------------"
}

function blue_title() {
    echo
    echo "======================================================"
    echo -e "\e[1;94;40m$1\e[0m"
    echo "------------------------------------------------------"
}

function bold_green() {
    setFlagsString "$1" "$2"
    echo $FLAGS "\e[1;92;40m${STRING}\e[0m"
}

function bold_blue() {
    setFlagsString "$1" "$2"
    echo $FLAGS "\e[1;94;40m${STRING}\e[0m"
}

function bold_yellow() {
    setFlagsString "$1" "$2"
    echo $FLAGS "\e[1;93;40m${STRING}\e[0m"
}

function bold_red() {
    setFlagsString "$1" "$2"
    echo $FLAGS "\e[1;91;40m${STRING}\e[0m"
}

