#!/bin/bash
source /usr/local/ece361-wrapper-prints
source /usr/local/ece361-lib

if [[ $# -ne 1 ]]; then
    INIT_CMD=$(basename $0) # Works w/ symbolic links
    bold_red "ERROR: Expecting exactly one parameter (the lab #)"
    bold_blue "Usage format:"
    blue "\t${INIT_CMD} <lab #>"
    exit 1
else
    LAB_NUM=$1
fi

# Sanity check of lab number to ensure it's not a string
checkLabNum ${LAB_NUM}
if [[ $? -ne 0 ]]; then
    exit 1
fi

# Open SSH connection
sshEECGOpenSess
if [[ $? -ne 0 ]]; then
    exit 1
fi

MOUNT_DIR=/usr/local/tester
sudo mkdir -p ${MOUNT_DIR}

# Mount (unmount first, just to be safe...)
sudo fusermount -q -u ${MOUNT_DIR}
sudo sshfs -o allow_other,reconnect ${SSHFLAGS} ${UTORID}@${EECG_HOST}:${EECG_WORKING_PATH} ${MOUNT_DIR}

# Run remote init script
INIT_SCRIPT=${MOUNT_DIR}/lab${LAB_NUM}-init
if [[ -f ${INIT_SCRIPT} ]]; then
    ${INIT_SCRIPT}
else
    bold_red "ERROR: Lab ${LAB_NUM} has not been released"
    bold_red "       If the lab has actually been released, please report this to the head TA"
fi

# Unmount
sudo fusermount -q -u ${MOUNT_DIR}

# Clean-up SSH control master
sshEECGCloseSess
