#!/bin/bash
source /usr/local/ece361-lib

if [[ $# -ne 1 ]]; then
    EXERCISE_CMD=$(basename $0) # Works w/ symbolic links
    bold_red "ERROR: Expecting exactly one parameter (the lab #)"
    bold_blue "Usage format:"
    blue "\t${EXERCISE_CMD} <lab #>"
    exit 1
else
    LAB_NUM=$1
fi

# Sanity check of lab number
checkLabNum ${LAB_NUM}
if [[ $? -ne 0 ]]; then
    exit 1
fi

# Open SSH connection
sshEECGOpenSess
if [[ $? -ne 0 ]]; then
    exit 1
fi

MOUNT_DIR=/usr/local/tester
sudo mkdir -p ${MOUNT_DIR}

# Mount (unmount first, just to be safe...)
sudo fusermount -q -u ${MOUNT_DIR}
sudo sshfs -o allow_other,reconnect ${SSHFLAGS} ${UTORID}@${EECG_HOST}:${EECG_WORKING_PATH} ${MOUNT_DIR}

# Run exercise
if [[ -f ${MOUNT_DIR}/run-public-tests.sh ]]; then
    ${MOUNT_DIR}/run-public-tests.sh ${LAB_NUM}
else
    bold_red "ERROR: Exerciser is not yet ready"
    bold_red "       If you believe this is a bug, please report this to the head TA"
fi

# Unmount
sudo fusermount -q -u ${MOUNT_DIR}

# Clean-up SSH control master
sshEECGCloseSess

