#!/bin/bash
source /usr/local/ece361-lib

if [[ $# -ne 1 ]]; then
    EXERCISE_CMD=$(basename $0) # Works w/ symbolic links
    bold_red "ERROR: Expecting exactly one parameter (the lab #)"
    bold_blue "Usage format:"
    blue "\t${EXERCISE_CMD} <lab #>"
    exit 1
else
    LAB_NUM=$1
fi

# Sanity check of lab number
checkLabNum ${LAB_NUM}
if [[ $? -ne 0 ]]; then
    exit 1
fi

# Open SSH connection
sshEECGOpenSess
if [[ $? -ne 0 ]]; then
    exit 1
fi

MOUNT_DIR=/usr/local/tester
sudo mkdir -p ${MOUNT_DIR}

# Mount (unmount first, just to be safe...)
# TODO: REMOTE PATH TO MOUNT NEEDS TO BE CHANGED TO REFLECT PATH PROVIDED BY EECG
sudo fusermount -q -u ${MOUNT_DIR}
sudo sshfs -o allow_other,reconnect ${SSHFLAGS} ${UTORID}@${EECG_HOST}:/cad2/ece361s/2020s ${MOUNT_DIR}

# Run exercise
${MOUNT_DIR}/run-public-tests.sh ${LAB_NUM}

# Unmount
sudo fusermount -q -u ${MOUNT_DIR}

# Clean-up SSH control master
sshEECGCloseSess

